twitter-to-kafka-service:
  twitter-topics:
    - java
    - spring boot
    - elasticsearch
    - prometheus
    - elk
    - microservices

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000