server:
  port: 8888

# override logback logging properties through yml file
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  cloud:
    config:
      profile: native
